spring:
  datasource:
    url: jdbc:sqlite:escola.db
    driver-class-name: org.sqlite.JDBC
  jpa:
    database-platform: org.hibernate.community.dialect.SQLiteDialect
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    defer-datasource-initialization: true # Mantemos essa, é importante
  sql: # <-- NOVA CONFIGURAÇÃO PARA GARANTIR EXECUÇÃO DE SCRIPTS
    init:
      mode: always
      # data-locations: classpath:/data.sql # Pode ser deixado comentado se o nome for padrão 'data.sql'